backend:
  name: github
  repo: stellake/belles-baseball-app
  branch: master
  
media_folder: static/assets
public_folder: /assets

collections:
  - label: "Pages"
    name: "pages"
    files:
      - name: whats-on
        label: What's on page
        file: data/whats-on.json
        extension: json
        fields:
          - { name: title, label: Title, widget: 'string' }
          - { name: description, label: Description, widget: 'string' }
          - name: calendar
            label: Calendar content
            widget: list
            fields:
            - { label: 'Month (short version)', name: 'month', widget: 'string' }
            - label: 'Events'
              name: 'events'
              widget: list
              fields:
              - { label: 'Description', name: 'description', widget: 'string' }
              - { label: 'Day (number)', name: 'day', widget: 'number', min: 1, max: 31 }
              - { label: 'Location', name: 'location', widget: 'string' }
